# Generated by Django 3.1.7 on 2021-03-20 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_auto_20210319_2007'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movies',
            old_name='director',
            new_name='directors',
        ),
        migrations.RenameField(
            model_name='movies',
            old_name='genre',
            new_name='genres',
        ),
    ]
